class ErrorCode:
    ERROR = -1
    NOT_CONNECTED = -2
    INVALID_COMMAND_SYNTAX = -3
    SHARING_NOT_FOUND = -4
    INVALID_PATH = -5
    COMMAND_NOT_RECOGNIZED = -6
    COMMAND_EXECUTION_FAILED = -7
    NOT_IMPLEMENTED = -8
    INVALID_TRANSACTION = -9
    UNEXPECTED_SERVER_RESPONSE = -10